# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
    # 分 時 天 月 週

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install requests_toolbelt
      - name: Run Python script
        env:
            url_add: ${{ secrets.url_add }}
            url_view: ${{ secrets.url_view }}
            url_delete: ${{ secrets.url_delete }}
            user_agent: ${{ secrets.user_agent }}
            cookie: ${{ secrets.cookie }}
            bot_token: ${{ secrets.bot_token }}
            chat_id: ${{ secrets.chat_id }}
        run: |
          python daily.py
